### ISSUE TITLE
Any idea to upgrade 183.*?

### ISSUE THREAD

**Issue by linux-china** [npryce/pottery-idea-plugin#1]
Now the plugin only supports IDEA 181, and IntelliJ IDEA 2018.3 starts with 183.*. Could you upgrade it?

```
  <idea-version since-build="181.5087" until-build="181.*"/>
```

**Comment by npryce** [comment]
I'd like to but I can't find that version of the IntelliJ plugin SDK in the Maven repo's.  Maybe because 
 2018.3 is still early access only.

Also I cannot work out how to make the SDK Gradle plugin generate a range of acceptable IntelliJ versions in the XML manifest.  Any help on this is most welcome.

**Comment by npryce** [comment]
Upping the Idea version to 2018.2 stops the plugin compiling!  I'll need to reduce the dependency on Idea platform UI components

**Comment by linux-china** [comment]
I'm not sure.  I think Kotlin Libraries are included by IntelliJ IDEA 2018.3 by default, and please refer IntelliJ IDEA 2018.3 EAP.app/Contents/lib for kotlin jars.

**Comment by npryce** [comment]
That’s the contents of the IDE itself, not the plugin SDK used for building plugins.

**Comment by npryce** [comment]
I'm happy to say I've worked out how to do it.

```
patchPluginXml {
    sinceBuild '182.*'
    untilBuild '183.*'
}
```

Expect a new plugin release soon, after I've tested it in both the current stable release and the EAP

**Comment by npryce** [comment]
I've published a version that will work in the EAP
